version: '3.7'

services:
  mongodb:
    image: mongo:4.4.2

  api:
    image: $LOCAL_IMAGE_ID
    environment:
      SERVICE_PUBLISH: '/api/kursinfo'
      SERVER_PORT: 3000
      MONGODB_URI: mongodb://mongodb/kursinfo
      API_KEYS_0: '?name=test&apiKey=1234&scope=read'
      LOGGING_ACCESS_LOG: 'true'
    ports:
      - 3000
    depends_on:
      - mongodb

  integration:
    build: ./test/integration
    depends_on:
      - api
